export default [
  { word: 'und', frequency: 16 },
  { word: 'mit', frequency: 15 },
  { word: 'oder', frequency: 11 },
  { word: 'im', frequency: 9 },
  { word: 'die', frequency: 8 },
  { word: 'der', frequency: 8 },
  { word: 'dem', frequency: 7 },
  { word: 'das', frequency: 7 },
  { word: 'sind', frequency: 6 },
  { word: 'auf', frequency: 6 },
  { word: 'in', frequency: 6 },
  { word: 'wir', frequency: 5 },
  { word: 'auch', frequency: 5 },
  { word: 'den', frequency: 5 },
  { word: 'eine', frequency: 5 },
  { word: 'zum', frequency: 4 },
  { word: 'job', frequency: 4 },
  { word: 'style', frequency: 4 },
  { word: 'zalando', frequency: 4 },
  { word: 'wie', frequency: 4 },
];
